network.host: 0.0.0.0
shield:
  authc:
    realms:
      esusers1:
        type: esusers
        order: 0
        files.users: /usr/share/elasticsearch/plugins/shield/config/users
        files.users_roles: /usr/share/elasticsearch/plugins/shield/config/users_roles
